version: '3.3'
services:
  db:
    image: mysql:8.0.32
    ports: 
      - 3306:3308
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: password
        - '3306:3306'
  web: 
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
