version: '3.3'
services:
  db:
    image:  mysql:5.7.42
    ports: 
      - 3306:3308
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: 172.28.0.3
  web: 
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password

