version: '3.3'
services:
  db:
    image: mysql:latest
    ports: 
      - 3306:3308
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  web: 
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password

